//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeMenuMvc.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CafeMenuEntities : DbContext
    {
        public CafeMenuEntities()
            : base(ConnectionString()) //base("name=CafeMenuEntities")
        {
        }

        public static string ConnectionString()
        {
            string server = "DESKTOP-JCSFFJ8";
            string databaseName = "CafeMenu";
            string userName = "sa";
            string password = "123";
            string metaData = "metadata=res://*/CafeMenuModel.csdl|res://*/CafeMenuModel.ssdl|res://*/CafeMenuModel.msl";
            return $"{metaData};provider=System.Data.SqlClient;provider connection string=\"data source={server};database={databaseName};user id={userName};password={password};MultipleActiveResultSets=True;App=EntityFramework\"";
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<PRODUCTPROPERTY> PRODUCTPROPERTY { get; set; }
        public virtual DbSet<PROPERTY> PROPERTY { get; set; }
        public virtual DbSet<USER> USER { get; set; }
    }
}
